### ISSUE TITLE
IllegalStateException

### ISSUE THREAD

**Issue by g0ldfinch** [sedatgoc/multiple-payload-downloader#1]
At work, I have 2 Java versions installed: JRE 8 and JDK 12. JDK 12 doesn't allow me to run this class because JavaFX is missing. On JRE 8, when downloading messages, I get this error:
[error.log](https://github.com/sedatgoc/multiple-payload-downloader/files/4033765/error.log)

The payload file gets created, but is of 0 size:
![payload](https://user-images.githubusercontent.com/22842680/71954246-c3a2b880-3238-11ea-9003-49f09f1edfb3.png)

Program screen, before I hit the _Download_ button, looks like this:
![Payload Downloader Parameters](https://user-images.githubusercontent.com/22842680/71954347-21cf9b80-3239-11ea-93ef-9e3b3e9870cb.png)

Below are my java versions:
[java_versions.log](https://github.com/sedatgoc/multiple-payload-downloader/files/4033774/java_versions.log)

I tried different selection criteria, but none of the messages gets downloaded. Besides, where I expect multiple messages to be downloaded, empty file is created for the first of them only, while in the logs I can see as many exceptions as many payloads I expect.

**Comment by sedatgoc** [comment]
Hello,
This exception does not prevent download messages. 

Can you check exists a log version of the message you want to download? (Can you share screen shoot from message monitor?)

14.01.2019 Edit : I checked my code after your comment and i updated JAR file. You can download new version.

Regards,
Sedat

**Comment by g0ldfinch** [comment]
Sorry, was so busy at work that couldn't respond. I tried the new version - now I don't have exceptions, but that doesn't fix the issue. The payload still can't be downloaded. E.g., when I select messages for Jan 13th, the program correctly identifies that there are 5 messages:

>Message count : 5
>52ecc4bc-35b9-11ea-83d5-0000001d29d2\OUTBOUND\1911250\EO\0\
>527ccf2d-35b9-11ea-bfa0-0000001d29d2\OUTBOUND\1911250\EO\0\
>51fe8032-35b9-11ea-a3a9-0000001d29d2\OUTBOUND\1911250\EO\0\
>51c524f8-35b9-11ea-a16d-0000001d29d2\OUTBOUND\1911250\EO\0\
>516f5ace-35b9-11ea-bbb6-0000001d29d2\OUTBOUND\1911250\EO\0\
>list end

However, as you will see on the attached screenshot, 1 file was created with 0 size, and the program shows _Downloading file.._

I'm attaching 2 screenshots, 1 from the message monitor and the other from the program, so that you can compare. If you have a switch for enabling debug logs, I can re-run the program with that enabled, so that you can get more clarification on what's going on.
![1 PO_MsgMonitor_MsgSelection](https://user-images.githubusercontent.com/22842680/72499521-35f14980-3886-11ea-93fc-6743e1462568.png)
![2 PD_at_work](https://user-images.githubusercontent.com/22842680/72499522-3689e000-3886-11ea-9d0b-774bbb04032a.png)

**Comment by sedatgoc** [comment]
Hello,

Did you see "Log Version" of the message which you want to download? 

![resim](https://user-images.githubusercontent.com/12969433/72614487-7367dc80-3943-11ea-89fd-05df255f1dc6.png)

![resim](https://user-images.githubusercontent.com/12969433/72614502-7d89db00-3943-11ea-89c5-c59e60e47d6a.png)

I updated JAR file. If you get any response, the Jar will print response.

![resim](https://user-images.githubusercontent.com/12969433/72615004-b37b8f00-3944-11ea-8dd4-f6168fcc512e.png)

**Comment by g0ldfinch** [comment]
Hi,

Yes, I first made sure that I specified the version that was logged, that
is, *MS*. Thanks for the new version, I'll try it on Monday when I get back
to the office.

**Comment by g0ldfinch** [comment]
Hi,
Tried again - nothing appears, both in the logs and in the files. The program correctly identifies messages and even starts creating the first of them, but then it doesn't do anything. The file is open for writing, but nothing is going on. Nothing in the _Download logs_ of the program, nor in the command prompt. Please see the detailed screenshot below.
![No_output_in_the_log](https://user-images.githubusercontent.com/22842680/72765852-972c6a80-3c42-11ea-9abf-fa1075892234.png)
Can it be related to roles and authorisations? E.g., I'm allowed to view and download the payload online, but not through the API. Can that be the case?

**Comment by sedatgoc** [comment]
> 
> 
> Hi,
> Tried again - nothing appears, both in the logs and in the files. The program correctly identifies messages and even starts creating the first of them, but then it doesn't do anything. The file is open for writing, but nothing is going on. Nothing in the _Download logs_ of the program, nor in the command prompt. Please see the detailed screenshot below.
> ![No_output_in_the_log](https://user-images.githubusercontent.com/22842680/72765852-972c6a80-3c42-11ea-9abf-fa1075892234.png)
> Can it be related to roles and authorisations? E.g., I'm allowed to view and download the payload online, but not through the API. Can that be the case?

Hi, Did you try to download AM step? I asked because it seems only the Log Version of AM step.

**Comment by g0ldfinch** [comment]
Hi again,
I finally managed to test this again. Yes, I tried to download all versions I could find. I had to adjust search parameters as each version had something different, e.g., BI had receiver component blank, or AM version had a different interface. None worked. Here is the combined screenshot of all 3 versions:
![image](https://user-images.githubusercontent.com/22842680/73404683-2f62d780-4346-11ea-85f7-7e1028d81b6b.png)
All I get is this:
![image](https://user-images.githubusercontent.com/22842680/73405011-07c03f00-4347-11ea-9a67-6d6a4657e2ec.png)
Or, for the allegedly logged version `AM`, this:
![image](https://user-images.githubusercontent.com/22842680/73405890-43f49f00-4349-11ea-8ca4-2945e46deaf4.png)

(Please note here that the interface in the `AM` version is the same in your program as in the `MS` version, otherwise the program can't find the message, though `AM` version shows a different interface name as you can see on the first screenshot.)

Another thing worth noting: while the program is doing nothing (from user perspective,) the file is open for writing and can't be modified. In addition, if I change search criteria in that state of the downloader and click the `Download` button again, then I get this error:
![image](https://user-images.githubusercontent.com/22842680/73405934-58d13280-4349-11ea-8aea-1263413e9ef7.png)

In addition, the JAR doesn't print anything new - the same stuff as in the original version. How can I enable debug mode, or is it even available?

**Comment by sedatgoc** [comment]
> 
> 
> Hi again,
> I finally managed to test this again. Yes, I tried to download all versions I could find. I had to adjust search parameters as each version had something different, e.g., BI had receiver component blank, or AM version had a different interface. None worked. Here is the combined screenshot of all 3 versions:
> ![image](https://user-images.githubusercontent.com/22842680/73404683-2f62d780-4346-11ea-85f7-7e1028d81b6b.png)
> All I get is this:
> ![image](https://user-images.githubusercontent.com/22842680/73405011-07c03f00-4347-11ea-9a67-6d6a4657e2ec.png)
> Or, for the allegedly logged version `AM`, this:
> ![image](https://user-images.githubusercontent.com/22842680/73405890-43f49f00-4349-11ea-8ca4-2945e46deaf4.png)
> 
> (Please note here that the interface in the `AM` version is the same in your program as in the `MS` version, otherwise the program can't find the message, though `AM` version shows a different interface name as you can see on the first screenshot.)
> 
> Another thing worth noting: while the program is doing nothing (from user perspective,) the file is open for writing and can't be modified. In addition, if I change search criteria in that state of the downloader and click the `Download` button again, then I get this error:
> ![image](https://user-images.githubusercontent.com/22842680/73405934-58d13280-4349-11ea-8aea-1263413e9ef7.png)
> 
> In addition, the JAR doesn't print anything new - the same stuff as in the original version. How can I enable debug mode, or is it even available?

I tried the same things and the tool downloaded messages. I think you are right maybe your user has not authorization for download messages. I want to help you but I don't know which role you need. 

I added this code for you. 

![resim](https://user-images.githubusercontent.com/12969433/73429218-270d9b00-434c-11ea-98c7-95755be027dc.png)

**Comment by g0ldfinch** [comment]
Thanks. At the moment, I'm getting this:

> Message count : 3
>682b8ea7-4368-11ea-8753-0000001d29d2\OUTBOUND\1911250\EO\0\
>4fabedb4-4366-11ea-8eaf-0000001d29d2\OUTBOUND\1911250\EO\0\
>3738e3d6-4364-11ea-a5a6-0000001d29d2\OUTBOUND\1911250\EO\0\
>list end
>Internal server error.

**Comment by g0ldfinch** [comment]
Found it in the logs in NWA. Hope this helps.
[HTTP500.log](https://github.com/sedatgoc/multiple-payload-downloader/files/4136736/HTTP500.log)
If it may help, our version of PO is `7.50.1.0`.

**Comment by sedatgoc** [comment]
> 
> 
> Found it in the logs in NWA. Hope this helps.
> [HTTP500.log](https://github.com/sedatgoc/multiple-payload-downloader/files/4136736/HTTP500.log)
> If it may help, our version of PO is `7.50.1.0`.

Hello. I checked that log and I found some notes for this error .

com.sap.engine.services.webservices.espbase.server.additions.exceptions.ProcessException: com.sap.SOA.wsr.030106 - No operation found using soap keys [urn:AdapterMessageMonitoringVi], [getLoggedMessageBytes], []. InterfaceMapping Object class: com.sap.engine.services.webservices.espbase.mappings.InterfaceMapping mappings: {BindingType=Soap, InterfaceMappingID=sap.com/com.sap.xi.mdt.beans_AdapterMessageMonitoring_basicPort}. 

Can you check these notes. 
https://launchpad.support.sap.com/#/notes/1763456
https://launchpad.support.sap.com/#/notes/1464338
https://launchpad.support.sap.com/#/notes/2519374
https://launchpad.support.sap.com/#/notes/1993336
https://launchpad.support.sap.com/#/notes/1507501

Also, I am researching solution for that error 👍

**Comment by g0ldfinch** [comment]
Thanks for **SNOTE**s.
1763456 - refers to NW 7.10
1464338 - not relevant as ours is 7.50 single stack server without HTTPS
1507501 - highest version the note applies to is 7.31

While 2519374 seems to be applicable to ver. 7.50, but the note it refers to, 1993336, is valid for versions up to **XI ADAPTER FRAMEWORK 7.40**. Our version of the `SAP_XIAF` component is `1000.7.50.1.0.20151022192600`, so I'm not sure whether it's possible to apply this note in our case...
